title: Ganesh Kalal
url: "https://gkalal64.github.io/"
baseurl: "/blog"

description:
This is a Demo description and will be updated soon when the content is available

author:
  name: Ganesh Kalal
  email: gkalal64@gmail.com
